accounts/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView, LogoutView,)
from .views import *
app_name = 'accounts'
urlpatterns = [
    path('sign_up/', MySignUpView.as_view(), name='sign_up'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name="logout"),]

easyRec/urls.py
from django.contrib import admin
from django.urls import path,include
from movies.views import movie_home
urlpatterns = [
    path('',movie_home,name='home'),
    path('admin/', admin.site.urls),
    path('movies/',include('movies.urls')),
    path('accounts/',include('accounts.urls')),
]

movies/urls.py
from django.urls import path
from movies.views import *

app_name='movies'

urlpatterns = [
    path('',movie_home,name='home'),
    path('detail',movie_detail,name='detail'),
    path('rate',rate_movie,name='rate'),
]

accounts/models.py
from django.db import models

# Create your models here.

movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    movie_id=models.CharField(max_length=10)
    movie_title=models.CharField(max_length=100)
    movie_genre=models.CharField(max_length=100)
    movie_plot=models.CharField(max_length=10000)
    movie_link=models.CharField(max_length=100)
    imdb_rating=models.CharField(max_length=100)

    def __str__(self):
        return self.movie_title

class Movie_Rating(models.Model):
    username = models.CharField(max_length=100)
    movie_id = models.CharField(max_length=100)
    rating=models.FloatField()

accounts/views.py
from django.shortcuts import render
from django.http import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.views import View
from django.contrib.auth import login

class MySignUpView(View):
    form_class = UserCreationForm
    template_name = 'accounts/sign_up.html'
    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            # <process form cleaned data>
            u = User.objects.create_user(
                    username=form.cleaned_data.get('username'),
                    password=form.cleaned_data.get('password1'),
                    is_active = True
            )
            login(request,u)
            # TODO Display message and redirect to login
            return HttpResponseRedirect('/')
        return render(request, self.template_name, {'form': form})

movies/views.py
from django.shortcuts import render
from django.http import HttpResponse
from movies import movies_utils
from movies.models import Movie_Rating
from easyRec.utils import similar_items
from django.contrib.auth.decorators import login_required

@login_required
def movie_home(request):
    popular_movies=movies_utils.popular_movies()
    action=movies_utils.top_charts("Action")
    scifi=movies_utils.top_charts("Sci-Fi")
    horror=movies_utils.top_charts("Horror")
    comedy=movies_utils.top_charts("Comedy")
    romance=movies_utils.top_charts("Romance")
    animation = movies_utils.top_charts("Animation")
    personalized=movies_utils.personalized_movies(str(request.user))
    data={}
    data['popular_movies']=popular_movies
    data['action']=action
    data['scifi']=scifi
    data['horror']=horror
    data['comedy']=comedy
    data['romance']=romance
    data['personalized']=personalized
    data['animation']=animation
    data['user']=str(request.user)

    #print(similar_items('m12'))

    #TODO render code
    return render(request,'movies/movies.html',data)

@login_required
def movie_detail(request):
    title=request.GET['title']
    movie_data=movies_utils.get_movie_details(title)
    similar_movies=movies_utils.similar_movies(title)
    data={}
    data['already_rated'] = False
    data['rating_value'] = 0
    qSet=Movie_Rating.objects.filter(username=str(request.user))
    for q in qSet:
        print(q.rating," ",q.movie_id, " \n\n")
        if q.movie_id == movie_data["movie_id"]:
            data['already_rated'] = True
            data['rating_value']=str(q.rating)

    data['movie_data']=movie_data
    data['similar_movies']=similar_movies

    #TODO render code
    return render(request,'movies/movie_details.html',data)


@login_required
def rate_movie(request):
    username=str(request.user)
    movie_id=request.GET["movie_id"]
    rating=request.GET["rating"]
    movies_utils.rate_movie(username,movie_id,rating)
    #TODO render code
    return HttpResponse("{'message':'success'}")

accounts/templates/accounts/login.html
{% load staticfiles %}
<head>
    <title>Sign In</title>
<style type="text/css">
        body
{
  margin:0;
  padding:0;
  font-family: 'Ubuntu', sans-serif;
  align-items:center;
  height:100vh;
  background: url("{% static 'images/accounts_bg.jpg' %}");
}
.login
{
  text-align:center;
  width:350px;
  border-radius:20px;
  box-sizing:border-box;
  padding:40px;
  background:#000000;
    background: rgba(0, 0, 0, 0.7);
  position:absolute;
  top:50%;
  left:50%;
  transform:translate(-50%,-50%);
}
.login h2
{
  margin: 0 0 20px;
  padding:0;
  font-size:30px;
  text-transform:uppercase;
  color: white;
}
.login .input-group
{
  position:relative;
  width:100%;
  margin-bottom:25px;
    box-shadow: none;
}
.login .input-group input
{
  height:50px;
  width:100%;
  box-sizing:border-box;
  font-size:18px;
  outline:none;
  border:1px solid #000;
  border-radius:20px;
  padding-left:20px;
  padding-right:30px;
}


.login .input-group input[type="submit"]
{
  background:#279CEB;
  border:none;
  box-shadow: none;
  cursor:pointer;
  font-wight:600;
  text-transform:uppercase;
  color:#fff;
}
.login .input-group input[type="submit"]:hover
{
  background:#31a9f9;
}
.login a
{
  font-size:12px;
  color:white;
  text-decoration:none;
  display:block;
  text-align:center;

}
.login a span
{
  color:#262626;
  font-weight:600;
}
.login a span:hover
{
  color:#ffc107;
}
.login span{
    color:white;
}
</style>
</head>

{%if user.is_authenticated %}
    <script>window.location.replace("{% url 'home' %}");</script>
{% endif %}

{% block content %}
    <body>
<div class="login">
    {% if next %}
        {% if user.is_authenticated %}
            <p style="color: #FF3A3A">Your account doesn't have access.</p>
        {% endif %}
    {% endif %}
  <h2>Sign In</h2>
  <form method="post" action="{% url 'accounts:login' %}">
      {% csrf_token %}
    <div class="input-group">
      <input type="text" name="username" id="id_username" required placeholder="Username">
    </div>
    <div class="input-group">
      <input type="password" name="password" required id="id_password" placeholder="Password">
    </div>
    <div class="input-group">
      <input type="submit" value="login">
        <input type="hidden" name="next" value="{{ next }}" />
    </div>
   </form>
    <div class="input-group">
    <span><a href="{% url 'accounts:sign_up' %}">Don't have an Account?</a></span>
    </div>
        {% if form.errors %}
        <p style="color: #FF3A3A">Failed! Login with correct credentials.</p>
    {% endif %}
</div>
</body>
{% endblock %}

accounts/templates/accounts/logout.html
{% block content %}
    <script>window.location.replace("{% url 'home' %}");</script>
  <div class="container">
      <div class="row justify-content-center align-items-center" style="height:80vh;">
          <div class="col-auto border p-3">
              You are logged out
          </div>
      </div>
  </div>
{% endblock %}

accounts/templates/accounts/sign_up.html
{% load staticfiles %}
<head>
    <title>Sign Up</title>
<style type="text/css">
        body
{
  margin:0;
  padding:0;
  font-family: 'Ubuntu', sans-serif;
  align-items:center;
  height:100vh;
  background: url("{% static 'images/accounts_bg.jpg' %}");
}
.login
{
  text-align:center;
  width:350px;
  border-radius:20px;
  box-sizing:border-box;
  padding:40px;
  background:#000000;
    background: rgba(0, 0, 0, 0.7);
  position:absolute;
  top:50%;
  left:50%;
  transform:translate(-50%,-50%);
}
.login h2
{
  margin: 0 0 20px;
  padding:0;
  font-size:30px;
  text-transform:uppercase;
  color: white;
}
.login .input-group
{
  position:relative;
  width:100%;
  margin-bottom:25px;
    box-shadow: none;
}
.login .input-group input
{
  height:50px;
  width:100%;
  box-sizing:border-box;
  font-size:18px;
  outline:none;
  border:1px solid #000;
  border-radius:20px;
  padding-left:20px;
  padding-right:30px;
}


.login .input-group input[type="submit"]
{
  background:#279CEB;
  border:none;
  box-shadow: none;
  cursor:pointer;
  font-wight:600;
  text-transform:uppercase;
  color:#fff;
}
.login .input-group input[type="submit"]:hover
{
  background:#31a9f9;
}
.login a
{
  font-size:12px;
  color:white;
  text-decoration:none;
  display:block;
  text-align:center;

}
.login a span
{
  color:#262626;
  font-weight:600;
}
.login a span:hover
{
  color:#ffc107;
}
.login span{
    color:white;
}
        .helptext{
            color: #279CEB;
        }
    .ul li{
        color: white;
    }
</style>
</head>
{%if user.is_authenticated %}
    <script>window.location.replace("{% url 'home' %}");</script>
{% endif %}
<body>
{% block content %}
<div class="login">
  <h2>Sign Up</h2>
  <form method="post" action="">
      {% csrf_token %}
    <div class="input-group">
      <input type="text" name="username" required id="id_username" placeholder="Username">
    </div>
    <div class="input-group">
      <input type="password" name="password1" required id="id_password1" placeholder="Password">
    </div>
       <div class="input-group">
      <input type="password" name="password2" required id="id_password2" placeholder=" Confirm Password">
    </div>
    <div class="input-group">
      <input type="submit" value="Submit">
        <input type="hidden" name="next" value="" />
    </div>
   </form>
    <div class="input-group">
    <span><a href="{% url 'accounts:login' %}">Already have an Account?</a></span>
    </div>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <p style="color: #FF3A3A">{{ error}}</p>
            {% endfor %}
        {% endfor %}
    {% endif %}
</div>
{% endblock %}
</body>

movies/templates/movies/movie_details.html
{% load staticfiles %}
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>{{ movie_data.movie_title }}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
<style type="text/css">
    @import url(https://fonts.googleapis.com/css?family=Lato:400,300,700);
@import url(https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css);
*, *:before, *:after {
  box-sizing: border-box;
}
body {
  overflow:hidden;
}
a {
  text-decoration: none;
  color: #5C7FB8;
}

a:hover {
  text-decoration: underline;
}

.movie-card {
  font: 14px/22px "Lato", Arial, sans-serif;
  color: #A9A8A3;
  padding: 40px 0;
}

.container {
  margin: 0 auto;
  width: 780px;
  height: 640px;
  background: #F0F0ED;
  border-radius: 5px;
  position: relative;
}

.hero {
  height: 342px;
  margin: 0;
  position: relative;
  overflow: hidden;
  z-index: 1;
  border-top-left-radius: 5px;
  border-top-right-radius: 5px;
}

.hero:before {
  content: '';
  width: 100%;
  height: 100%;
  position: absolute;
  overflow: hidden;
  top: 0;
  left: 0;
  background: url("{% static 'images/blur_bg.jpg' %}");
  background-repeat: no-repeat;
  background-size: cover;
  z-index: -1;
{#  -webkit-transform: skewY(-2.2deg);#}
{#          transform: skewY(-2.2deg);#}
  -webkit-transform-origin: 0 0;
          transform-origin: 0 0;
  -webkit-backface-visibility: hidden;
}

.cover {
  position: absolute;
  top: 160px;
  left: 40px;
  z-index: 2;
}

.details {
  padding: 190px 0 0 280px;
}
.details .title1 {
  color: white;
  font-size: 44px;
  margin-bottom: 13px;
  position: relative;
  line-height: 1.0;
}
.details .title1 span {
  position: absolute;
  top: 3px;
  margin-left: 12px;
  background: #C4AF3D;
  border-radius: 5px;
  color: #544C21;
  font-size: 14px;
  padding: 0px 4px;
}
.details .title2 {
  color: #C7C1BA;
  font-size: 23px;
  font-weight: 300;
  margin-bottom: 15px;
}
.details .likes {
  margin-left: 24px;
}
.details .likes:before {
  content: url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/icon_like.png");
  position: relative;
  top: 2px;
  padding-right: 7px;
}

.description {
  bottom: 0px;
  height: 200px;
  font-size: 16px;
  line-height: 26px;
  color: #B1B0AC;
}

.column1 {
  padding-left: 50px;
  padding-top: 120px;
  width: 220px;
  float: left;
  text-align: center;
}

.tag {
  background: white;
  border-radius: 10px;
  padding: 3px 8px;
  font-size: 14px;
  margin-right: 4px;
  line-height: 35px;
  cursor: pointer;
}

.tag:hover {
  background: #ddd;
}

.column2 {
  padding-left: 41px;
  padding-top: 30px;
  margin-left: 20px;
  width: 480px;
  float: left;
}


fieldset, label {
  margin: 0;
  padding: 0;
}

/****** Style Star Rating Widget *****/
.rating {
  border: none;
  float: left;
}

.rating > input {
  display: none;
}

.rating > label:before {
  margin: 5px;
  margin-top: 0;
  font-size: 1.5em;
  font-family: FontAwesome;
  display: inline-block;
  content: "\f005";
}

.rating > .half:before {
  content: "\f089";
  position: absolute;
}

.rating > label {
  color: #ddd;
  float: right;
}

/***** CSS Magic to Highlight Stars on Hover *****/
.rating > input:checked ~ label,
.rating:not(:checked) > label:hover,
.rating:not(:checked) > label:hover ~ label {
  color: #FFD700;
}

/* hover previous stars in list */
.rating > input:checked + label:hover,
.rating > input:checked ~ label:hover,
.rating > label:hover ~ input:checked ~ label,
.rating > input:checked ~ label:hover ~ label {
  color: #FFED85;
}
a[data-tooltip] {
  position: relative;
}
a[data-tooltip]::before,
a[data-tooltip]::after {
  position: absolute;
  display: none;
  opacity: 0.85;
}

a[data-tooltip]::before {
  /*
   * using data-tooltip instead of title so we
   * don't have the real tooltip overlapping
   */
  content: attr(data-tooltip);
  background: #000;
  color: #fff;
  font-size: 13px;
  padding: 5px;
  border-radius: 5px;
  /* we don't want the text to wrap */
  white-space: nowrap;
  text-decoration: none;
}

a[data-tooltip]::after {
  width: 0;
  height: 0;
  border: 6px solid transparent;
  content: '';
}

a[data-tooltip]:hover::before,
a[data-tooltip]:hover::after {
  display: block;
}

/** positioning **/
/* top tooltip */
a[data-tooltip][data-placement="top"]::before {
  bottom: 100%;
  left: 0;
  margin-bottom: 40px;
}

a[data-tooltip][data-placement="top"]::after {
  border-top-color: #000;
  border-bottom: none;
  bottom: 50px;
  left: 20px;
  margin-bottom: 4px;
}
    .inline-block {
   display: inline-block;
}
    .similar-movies {
        display: flex;
        flex-float: row wrap;
        justify-content: space-around;
        align-content: center;
    }

    .fx {
        display:flex;
    }
    a {
        text-decoration: none;
    }
</style>
</head>
<body>
  <div class="fluid-container">
    <div class="title-bar fx" style="justify-content: space-between;padding:15px;">
        <div class="left">
            <a href="/" class="btn red"><p class="bold" style="font-size:24px;">Movies</p></a>
        </div>
        <div class="profile-box name-logout">
            <a href="{% url 'accounts:logout' %}" class="btn red" style="font-size:20px;">{{ user }} | Logout</a>
        </div>
    </div>
    <img src="{{ movie_data.movie_link }}" width="187px" height="282px" alt="cover" class="cover" />
    <div class="hero">
      <div class="details">
        <div class="title1">{{ movie_data.movie_title }}</div>
            <span class="tag" style="margin-right:0px;color:black;">{{ movie_data.movie_genre }}</span>
      </div>
    </div>
    <div class="description">
       <div class="column1" style="padding-left:200px;padding-top:0px;">
        <div class="container" style="height: 300px;width: 1000px;margin-left:100px;">
          <div style="padding:20px;margin-top:30px;" class="fx">
            <p style="font-weight: bold;font-size: 28px;font-family:Sans-Serif;color:black;margin-bottom: 10px;align-self: center">
                Similar Movies to this item
            </p>
            <ul class="similar-movies">
                {% for p in similar_movies %}
                    <li style="margin-left: 20px" class="inline-block">
                        <a  href="{% url 'movies:detail' %}?title={{ p.movie_title }}">
                            <img src="{{ p.movie_link }}" height="195px" width="130px" alt="" />
                            <p style="width: 128px">{{ p.movie_title}}</p>
                        </a>
                    </li>
                    <a href="{% url 'movies:detail' %}?title={{ p.movie_title }}"></a>
                {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>


<script type="text/javascript">
    window.onload = function() {
        rateAjax();
    }
    function rateAjax(){
        var ratingValue = +"{{ rating_value }}";
        ratingValue = ratingValue + 3;
            var url="{% url 'movies:rate' %}?movie_id={{movie_data.movie_id}}&rating="+ratingValue;
			console.log(url)
			var req=new XMLHttpRequest();
			req.open('GET',url)
			req.onload=function()
			{
				console.log(req.responseText);
			};
			req.send();
	}
</script>